name: Delete Merged Branches

on:
  # This workflow can be triggered manually from the Actions tab
  workflow_dispatch:
  # Additionally, you can schedule it to run at specific intervals
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at 00:00

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Delete merged branches
      run: |
        git fetch origin
        # Get a list of all branches that are merged into origin/HEAD
        MERGED_BRANCHES=$(git branch -r --merged origin/HEAD | grep -v '/HEAD' | grep -v '/main' | sed 's/origin\///')
        for branch in $MERGED_BRANCHES; do
          # Delete the branch remotely
          gh repo view --json defaultBranchRef.name | jq -r '.defaultBranchRef.name' | xargs git push origin --delete $branch
        done
