# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup branch 'workflow/wakatime_stats'
      run: |
        git fetch origin
        git checkout -B workflow/wakatime_stats
        git reset --hard origin/main

    - name: Update WakaTime stats
      uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      
    - name: Push branch
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update WakaTime stats" || echo "No changes to commit"
        git push -f origin workflow/wakatime_stats

    - name: Create Pull Request if not exists
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update WakaTime stats"
        body: "This PR updates the WakaTime stats."
        branch: workflow/wakatime_stats
        base: main
        modify: true
