name: Scheduled WakaTime Update

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allow to automate by schedule
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup ENV values
      run: |
        echo "BRANCH_NAME=workflow/wakatime_stats" >> $GITHUB_ENV
        echo "BOT_ACTION_NAME='GitHub Actions Bot'" >> $GITHUB_ENV
        echo "BOT_ACTION_MAIL='actions@github.com'" >> $GITHUB_ENV

    - name: Set up GitHub CLI
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Sync branch '${{ env.BRANCH_NAME }}'
      run: |
        git config --global user.name ${{ env.BOT_ACTION_NAME }}
        git config --global user.email ${{ env.BOT_ACTION_MAIL }}
        git fetch origin
        git checkout -B ${{ env.BRANCH_NAME }}
        git reset --hard origin/main
        git push -f origin ${{ env.BRANCH_NAME }}

    - name: Update README using WakaTime
      id: wakatime
      uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
        AUTHOR_NAME: ${{ env.BOT_ACTION_NAME }}
        AUTHOR_EMAIL: ${{ env.BOT_ACTION_MAIL }}
        TARGET_BRANCH: ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      run: |
        git fetch origin
        git pull origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request if not exists
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update WakaTime stats"
        body: "This PR updates the WakaTime stats."
        branch: ${{ env.BRANCH_NAME }}
        base: main
        modify: true
