name: Scheduled WakaTime Update

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allow to automate by schedule
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set branch name based
      run: echo "BRANCH_NAME=workflow/wakatime_stats" >> $GITHUB_ENV

    - name: Setup branch '${{ env.BRANCH_NAME }}'
      run: |
        git fetch origin
        git checkout -B $BRANCH_NAME
        git reset --hard origin/main

    - name: Clone repo in a separate directory and update WakaTime stats
      run: |
        git clone ${{ github.repository }} temp_clone
        cd temp_clone
        git checkout -B ${{ env.BRANCH_NAME }}
        git reset --hard origin/main
        uses: athul/waka-readme@master
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        cp README.md ../
        cd ..
        rm -rf temp_clone

    - name: Commit and push branch
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update WakaTime stats" || echo "No changes to commit"
        git push -f origin ${{ env.BRANCH_NAME }}

    - name: Create Pull Request if not exists
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update WakaTime stats"
        body: "This PR updates the WakaTime stats."
        branch: ${{ env.BRANCH_NAME }}
        base: main
        modify: true
