name: Scheduled WakaTime Update

on:
  schedule:
    - cron: '0 * * * *'  # This schedules the workflow to run at most every 5 minutes using UTC time.

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set branch name based on current date-time
      run: echo "BRANCH_NAME=wakatime/$(date +'%Y%m%d%H%M')_stats" >> $GITHUB_ENV

    - name: Checkout new branch
      run: |
        git checkout -b $BRANCH_NAME

    - name: Update WakaTime stats
      uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      
    - name: Push branch
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Update WakaTime stats"
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Update WakaTime stats"
        body: "This PR updates the WakaTime stats."
        branch: ${{ env.BRANCH_NAME }}
        base: main

